# version: '3'

# services:
#   web:
#     build: .
#     command: python manage.py makemigrations && python manage.py migrate &&python manage.py runserver
#     container_name: todo
#     volumes:
#       - .:/todo
#     ports:
#       - "8000:8000"


version: '3'

services:
  web:
    image: sanjeevstory/todo:tagname
    container_name: todo
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py makemigrations || exit 1 && 
               python manage.py migrate || exit 1 && 
               python manage.py runserver 0.0.0.0:8000"

