# Generated by Django 4.2.2 on 2024-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
            ],
        ),
    ]
