# Generated by Django 4.2.2 on 2025-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_todotask"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoTask1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("task", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150)),
                ("address_status", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name="todotask",
            old_name="address",
            new_name="address_status",
        ),
    ]
