# Generated by Django 4.2.2 on 2025-05-12 11:35

# from django.db import migrations, models


# class Migration(migrations.Migration):
#     dependencies = [
#         ("app", "0005_todotask1_rename_address_todotask_address_status"),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name="todotask1",
#             name="task_id",
#             field=models.CharField(default=1, max_length=100),
#             preserve_default=False,
#         ),
#     ]
